package formulacmd

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"

	"github.com/sjzsdu/tt/internal/agents"
)

const formulaLong = `Formula is a typed workflow system for turning repeatable work into
resumable, inspectable TOML recipes.

What a formula can model:
  - agent work       normal [[steps]] with agent.name/model overrides
  - local scripts    execution = "script" with safe argv commands
  - human input      execution = "human_input" for fixed forms, or form = true
                     for dynamic clarification generated by an agent
  - branching        condition = "step-id.field == value"
  - loops            [steps.loop] with body steps and until conditions
  - retries          [steps.retry] for attempt/evaluate/fix cycles

Data flow:
  - each step output is saved under its step id by default
  - downstream steps reference prior output with input_context = ["step-id"]
  - JSON fields can be addressed as step-id.field in conditions
  - runtime env is always available as env.cwd, env.git.branch, env.git.is_repo
  - use clear, stable step ids; no output_key is needed for normal authoring

Common commands:
  tt formula list
  tt formula help bug-fix
  tt formula show bug-fix
  tt formula copy bug-fix ./bug-fix.toml
  tt formula compile bug-fix
  tt formula run bug-fix "login button returns 500"
  tt formula runs

Minimal TOML shape:
  formula = "my-workflow"
  version = 1
  type = "workflow"

  [vars]
  topic = { description = "What to work on", required = true }

  [[steps]]
  id = "analyze"
  title = "Analyze request"
  description = "Use repo {{env.git.repo}} on branch {{env.git.branch}}. Output ONLY compact JSON: {\"kind\":\"frontend\"}."
  agent.name = "assistant"

  [[steps]]
  id = "frontend-plan"
  title = "Plan frontend work"
  depends_on = ["analyze"]
  input_context = ["analyze"]
  condition = "analyze.kind == frontend"

Authoring tips:
  - prefer one cohesive step over multiple bookkeeping steps
  - use form = true when missing information is dynamic
  - use execution = "human_input" only for fixed approvals/choices
  - keep agent outputs compact JSON when later steps branch on them
  - inspect available agents with: tt agent --list`

func New(deps Dependencies) *cobra.Command {
	configureDependencies(deps)
	app := &App{}

	formulaCmd := &cobra.Command{
		Use:   "formula",
		Short: "Manage and run formula workflows",
		Long:  formulaLong,
		PersistentPreRun: func(cmd *cobra.Command, args []string) {
			app.installOptions()
		},
	}
	formulaCmd.PersistentFlags().StringVarP(&app.opts.Dir, "dir", "d", "", "formula search directory (default: .tt/formulas, ~/.tt/formulas)")
	formulaCmd.PersistentFlags().StringArrayVar(&app.opts.Vars, "var", nil, "variable override (key=value, repeatable)")

	formulaHelpCmd := app.newFormulaHelpCmd()
	formulaListCmd := app.newFormulaListCmd()
	formulaShowCmd := app.newFormulaShowCmd()
	formulaCompileCmd := app.newFormulaCompileCmd()
	formulaValidateCmd := newFormulaValidateCmd()
	formulaCopyCmd := newFormulaCopyCmd()
	formulaCreateCmd := app.newFormulaCreateCmd()
	formulaOptimizeCmd := app.newFormulaOptimizeCmd()
	formulaRunCmd := app.newFormulaRunCmd()
	formulaRunsCmd := app.newFormulaRunsCmd()
	formulaScheduleCmd := app.newFormulaScheduleCmd()

	formulaCmd.AddCommand(formulaHelpCmd)
	formulaCmd.AddCommand(formulaListCmd)
	formulaCmd.AddCommand(formulaShowCmd)
	formulaCmd.AddCommand(formulaCompileCmd)
	formulaCmd.AddCommand(formulaValidateCmd)
	formulaCmd.AddCommand(formulaCopyCmd)
	formulaCmd.AddCommand(formulaCreateCmd)
	formulaCmd.AddCommand(formulaOptimizeCmd)
	formulaCmd.AddCommand(formulaRunCmd)
	formulaCmd.AddCommand(formulaRunsCmd)
	formulaCmd.AddCommand(formulaScheduleCmd)

	return formulaCmd
}

func (a *App) newFormulaScheduleCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "schedule <name> [required-var-value]",
		Short: "Run a formula repeatedly on an interval or cron schedule",
		Long: `Run a formula repeatedly in the foreground until interrupted.

Exactly one schedule source is required:
  --every 2m
  --cron "*/2 * * * *"

The scheduled formula run defaults to no live dashboard so unattended runs do not
block. Pass --web to keep the normal dashboard behavior for each run.`,
		Args: cobra.MinimumNArgs(1),
		RunE: runFormulaSchedule,
	}
	cmd.Flags().StringVar(&a.opts.ScheduleEvery, "every", "", "fixed interval between formula runs, such as 30s, 2m, or 1h")
	cmd.Flags().StringVar(&a.opts.ScheduleCron, "cron", "", "5-field crontab expression, such as '*/2 * * * *'")
	cmd.Flags().IntVar(&a.opts.ScheduleMaxRuns, "max-runs", 0, "stop after this many runs; 0 means run forever")
	cmd.Flags().BoolVar(&a.opts.ScheduleRunNow, "run-now", false, "run once immediately before waiting for the first scheduled tick")
	cmd.Flags().BoolVar(&a.opts.ScheduleStopOnError, "stop-on-error", false, "stop the scheduler after a failed formula run")
	cmd.Flags().BoolVar(&a.opts.ScheduleWeb, "web", false, "enable the live dashboard for each scheduled run")
	cmd.Flags().StringVar(&a.opts.Agent, "agent", agents.AssistantID, "default agent for steps without explicit agent config")
	cmd.Flags().StringVar(&a.opts.Model, "model", "", "default model override")
	cmd.Flags().StringVar(&a.opts.ExternalDriver, "ext-driver", "", "default external_agent driver (jcode|codex|opencode|forge|bl); empty falls back to jcode")
	cmd.Flags().StringVar(&a.opts.Session, "session", "cli:formula", "session key prefix")
	cmd.Flags().BoolVar(&a.opts.DryRun, "dry-run", false, "print execution plan without running")
	cmd.Flags().BoolVar(&a.opts.Debug, "debug", false, "enable debug logging")
	cmd.Flags().BoolVarP(&a.opts.Verbose, "verbose", "v", false, "show full output of each step")
	cmd.Flags().BoolVar(&a.opts.NoSave, "no-save", false, "do not save formula run state under .tt/runs/formula")
	cmd.Flags().BoolVar(&a.opts.NoScript, "no-script", false, "disable formula script steps for this run")
	cmd.Flags().BoolVar(&a.opts.AllowShell, "allow-shell-script", false, "allow script steps to run through an explicit shell")
	return cmd
}

func (a *App) newFormulaListCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List available formulas",
		Args:  cobra.NoArgs,
		RunE:  runFormulaList,
	}
	cmd.Flags().BoolVar(&a.opts.ListBuiltin, "builtin", false, "show only builtin formulas")
	cmd.Flags().BoolVar(&a.opts.ListUser, "user", false, "show only user formulas from search paths")
	cmd.Flags().StringVar(&a.opts.ListCategory, "category", "", "filter formulas by category")
	return cmd
}

func (a *App) newFormulaShowCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "show [name]",
		Short: "Show formula details",
		Long: `Show formula details. Without a name, lists all formulas.
With --markdown and no name, generates a combined Markdown preview of all formulas.`,
		Args: cobra.MaximumNArgs(1),
		RunE: runFormulaShow,
	}
	cmd.Flags().BoolVar(&a.opts.Markdown, "markdown", false, "render formula as Markdown with Mermaid diagram and preview in browser")
	cmd.Flags().BoolVar(&a.opts.MarkdownHideGraphVars, "hide-graph-vars", false, "hide variable nodes and variable edges in the Markdown dependency graph")
	cmd.Flags().IntVarP(&a.opts.Port, "port", "p", 9598, "web server port for --markdown preview")
	return cmd
}

func (a *App) newFormulaCompileCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "compile <name>",
		Short: "Compile a formula and show the recipe",
		Args:  cobra.ExactArgs(1),
		RunE:  runFormulaCompile,
	}
	return cmd
}

func newFormulaValidateCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "validate <file>",
		Short: "Validate a formula file",
		Args:  cobra.ExactArgs(1),
		RunE:  runFormulaValidate,
	}
}

func newFormulaCopyCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "copy <name> [output]",
		Short: "Copy a builtin formula to a local TOML file",
		Args:  cobra.RangeArgs(1, 2),
		RunE:  runFormulaCopy,
	}
}

func (a *App) newFormulaCreateCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "create <name> <prompt...>",
		Short: "Create a formula with the embedded formula-writer agent",
		Long: `Create a formula template from a natural-language prompt.

The embedded formula-writer agent designs the workflow, chooses agent/script
steps, and emits TOML. By default the result is written to .tt/formulas/<name>.toml
or to --output when provided, then validated locally. Use --stdout to print only.`,
		Args: cobra.MinimumNArgs(2),
		RunE: runFormulaCreate,
	}
	cmd.Flags().StringVarP(&a.opts.CreateOutput, "output", "o", "", "output formula file path (default: .tt/formulas/<name>.toml or --dir/<name>.toml)")
	cmd.Flags().BoolVarP(&a.opts.CreateForce, "force", "f", false, "overwrite an existing formula file")
	cmd.Flags().BoolVar(&a.opts.CreateStdout, "stdout", false, "print generated formula instead of writing a file")
	cmd.Flags().StringVar(&a.opts.Model, "model", "", "model override for formula-writer agent")
	cmd.Flags().BoolVar(&a.opts.Debug, "debug", false, "enable debug logging")
	return cmd
}

func (a *App) newFormulaOptimizeCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "optimize <name> <suggestion...>",
		Short: "Optimize an existing formula with the embedded formula-writer agent",
		Long: `Optimize an existing formula from natural-language suggestions.

The command first resolves <name> from the formula search paths. If the formula
does not exist, it fails immediately and does not call the agent. Otherwise it
sends the current formula TOML plus your suggestions to the embedded
formula-writer agent, writes the improved formula back to the source file by
default, and validates the result locally. Use --stdout to preview only.`,
		Args: cobra.MinimumNArgs(2),
		RunE: runFormulaOptimize,
	}
	cmd.Flags().StringVarP(&a.opts.OptimizeOutput, "output", "o", "", "write optimized formula to this path instead of overwriting the source")
	cmd.Flags().BoolVar(&a.opts.OptimizeStdout, "stdout", false, "print optimized formula instead of writing a file")
	cmd.Flags().BoolVar(&a.opts.OptimizeBuiltin, "built-in", false, "optimize a builtin formula and write result to your formula directory unless --output/--stdout is set")
	cmd.Flags().StringVar(&a.opts.Model, "model", "", "model override for formula-writer agent")
	cmd.Flags().BoolVar(&a.opts.Debug, "debug", false, "enable debug logging")
	return cmd
}

func (a *App) newFormulaRunCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "run [name] [required-var-value]",
		Short: "Execute a formula with picoclaw agents",
		Long: `Execute a formula by running each step through the configured agent.
Steps are executed in dependency order, with parallel steps running concurrently.

Runtime control notes:
  - Steps without explicit agent config use embedded agent "assistant" by default.
  - condition expressions are evaluated at runtime against saved step-id output data.
  - loop.until expressions are evaluated after each loop iteration.
  - start/end boundary steps are real recipe steps; generated boundaries are noop.`,
		Args: func(cmd *cobra.Command, args []string) error {
			if len(args) == 0 && strings.TrimSpace(a.opts.File) == "" {
				return fmt.Errorf("requires a formula name or --file")
			}
			return nil
		},
		RunE: runFormulaRun,
	}
	cmd.Flags().StringVar(&a.opts.File, "file", "", "TOML file containing formula and [vars] for this run")
	cmd.Flags().StringVar(&a.opts.Agent, "agent", agents.AssistantID, "default agent for steps without explicit agent config")
	cmd.Flags().StringVar(&a.opts.Model, "model", "", "default model override")
	cmd.Flags().StringVar(&a.opts.ExternalDriver, "ext-driver", "", "default external_agent driver (jcode|codex|opencode|forge|bl); empty falls back to jcode")
	cmd.Flags().StringVar(&a.opts.Session, "session", "cli:formula", "session key prefix")
	cmd.Flags().BoolVar(&a.opts.Web, "web", true, "show a live web dashboard while the formula runs (default true; kept for compatibility)")
	cmd.Flags().BoolVar(&a.opts.NoWeb, "no-web", false, "do not open or keep a live web dashboard for this formula run")
	cmd.Flags().IntVar(&a.opts.WebPort, "web-port", 9705, "dashboard web server port")
	cmd.Flags().BoolVar(&a.opts.DryRun, "dry-run", false, "print execution plan without running")
	cmd.Flags().BoolVar(&a.opts.Debug, "debug", false, "enable debug logging")
	cmd.Flags().BoolVarP(&a.opts.Verbose, "verbose", "v", false, "show full output of each step")
	cmd.Flags().BoolVar(&a.opts.NoSave, "no-save", false, "do not save formula run state under .tt/runs/formula")
	cmd.Flags().BoolVar(&a.opts.NoScript, "no-script", false, "disable formula script steps for this run")
	cmd.Flags().BoolVar(&a.opts.AllowShell, "allow-shell-script", false, "allow script steps to run through an explicit shell")

	cmd.AddCommand(a.newFormulaRunOpenCmd())
	cmd.AddCommand(a.newFormulaRunShowCmd())
	cmd.AddCommand(a.newFormulaRunRmCmd())
	cmd.AddCommand(a.newFormulaRunResumeCmd())
	cmd.AddCommand(a.newFormulaRunInputCmd())
	cmd.AddCommand(a.newFormulaRunChatCmd())
	return cmd
}

func (a *App) newFormulaRunsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "runs",
		Short: "List saved formula runs",
		Args:  cobra.NoArgs,
		RunE:  runFormulaRuns,
	}
	cmd.Flags().IntVar(&a.opts.RunsLimit, "limit", 20, "maximum number of runs to list")
	cmd.Flags().StringVar(&a.opts.RunsFormula, "formula", "", "filter runs by formula name")
	cmd.Flags().StringVar(&a.opts.RunsStatus, "status", "", "filter runs by status")
	return cmd
}

func (a *App) newFormulaRunOpenCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "open [run-id|latest]",
		Short: "Open a saved formula run dashboard",
		Args:  cobra.MaximumNArgs(1),
		RunE:  runFormulaRunOpen,
	}
	cmd.Flags().IntVar(&a.opts.WebPort, "web-port", 9705, "dashboard web server port")
	return cmd
}

func (a *App) newFormulaRunShowCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "show [run-id|latest]",
		Short: "Show a saved formula run",
		Args:  cobra.MaximumNArgs(1),
		RunE:  runFormulaRunShow,
	}
	cmd.Flags().StringVar(&a.opts.RunShowStep, "step", "", "show details for a specific step id")
	return cmd
}

func (a *App) newFormulaRunRmCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "rm <run-id>",
		Short: "Delete a saved formula run",
		Args:  cobra.ExactArgs(1),
		RunE:  runFormulaRunRm,
	}
	cmd.Flags().BoolVarP(&a.opts.RunRmYes, "yes", "y", false, "confirm deletion without prompting")
	return cmd
}

func (a *App) newFormulaRunResumeCmd() *cobra.Command {
	return &cobra.Command{
		Use:   "resume [run-id|latest]",
		Short: "Resume a saved formula run from unfinished steps",
		Args:  cobra.MaximumNArgs(1),
		RunE:  runFormulaRunResume,
	}
}

func (a *App) newFormulaRunInputCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "input [run-id|latest] <step-id>",
		Short: "Submit human input for a waiting formula step and resume the run",
		Args:  cobra.RangeArgs(1, 2),
		RunE:  runFormulaRunInput,
	}
	cmd.Flags().StringArrayVar(&a.opts.InputFields, "field", nil, "human input field value (key=value, repeatable; duplicate keys become arrays)")
	return cmd
}

func (a *App) newFormulaRunChatCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:   "chat [run-id|latest] <step-id>",
		Short: "Chat with the agent of a completed step to refine its output and rerun",
		Long: `Chat with the agent that ran a specific step to provide feedback and refine its output.
The agent will be re-run with your feedback appended to the prompt, and all downstream
steps will be re-executed as well.

Usage:
  tt formula run chat <run-id> <step-id>
  tt formula run chat latest <step-id>

You will be prompted to enter your feedback message interactively.`,
		Args: cobra.RangeArgs(1, 2),
		RunE: runFormulaRunChat,
	}
	return cmd
}
